Add documentation regarding authorization and access tokens
i-on-project/codegarten pull request #14
Opened 2021-04-03 15:39 UTC by PTKickass

This PR adds information about the following things:
- How to obtain a user access token from GitHub
- Reasons as to why we chose to use a GitHub App instead of OAuth App
- How to manage GitHub App installations and how to obtain their IDs
- How to access the GitHub API
- How to manage CodeGarten API Access, including how to generate Access Tokens

Closes gh-10.

2021-04-03 15:41 UTC, TiagoMMDavid approved these changes
Looks great to me!

2021-04-03 15:42 UTC, dvsshadow approved these changes

2021-04-06 14:11 UTC, pmhsfelix requested changes
See comments. We need interaction/sequence diagram before proceeding.

2021-04-06 14:11 UTC, pmhsfelix commented on docs/auth/app-comparison.md
> +* An OAuth application acts as an authenticated GitHub user (owner of the access token), while GitHub apps use their own identity
Suggestion: replace "act as" with "acts on behalf of"

2021-04-06 14:11 UTC, pmhsfelix commented on docs/auth/app-comparison.md
> +* GitHub apps are installed in organizations (by an admin) or in an user, while OAuth apps are authorized to access user resources (e.g repositories that an user can access)
- "or in an user" - something is not right
- "OAuth apps are authorised **by users** t access resources as the user"

2021-04-06 14:11 UTC, pmhsfelix commented on docs/auth/codegarten-api.md
> +After the CodeGarten IM gets a GitHub OAuth Access Token from the user, and after that token is stored in the database, the CodeGarten IM will generate a valid code to be exchanged by an API Access T
What does "IM" mean?

2021-04-06 14:11 UTC, pmhsfelix commented on docs/auth/github-api.md
> +To obtain an installation access token, the API will have an endpoint which will respond with the GitHub App installation URI, which will be used to install the GitHub App to an organization. The bro
I don't understand the "which will respond with the GitHub App installation URI".

2021-04-06 14:11 UTC, pmhsfelix commented on docs/auth/github-api.md
> +To obtain a user's access token, the API will have an endpoint which will respond with an URI from the CodeGarten IM module. This URI will redirect the browser to the GitHub App's OAuth URI, which in
An interaction diagram, preferably in text format, would be useful. Example:
```
- Client opens browser with an URI containing an authorization request to CG (CodeGarten)
- B --> CG/AS: GET authorization request-1, with scope=TODO
- B <-- CG/AS: redirect with an URI containing an authorization request to GH (GitHub), with scope=TODO
- B --> GH/AS: GET authorization-request-2
- B <-> GH/AS: interactive user authentication and consent
- B <-- GH/AS: redirect with Location=authorization-response-2
- B --> CG/AS: GET authorisation-response-2 (contains code issued by GH)
...
```
Also, this diagram should include what is done by internally by CG on each step.

2021-04-13 13:44 UTC, pmhsfelix approved these changes
Left some notes with additional information that should be present in the design document. Doesn't need to be done on this PR. Can be done in parallel with the implementation.

2021-04-13 13:44 UTC, pmhsfelix commented on docs/auth/codegarten-api.md
> +In order to obtain a CodeGarten API Access Token, it's required to authenticate via GitHub. This process is described in the [corresponding documentation](github-api.md#user-access-token). It's also
"sending the client ID through the query string" - this follows the OAuth protocol, right?

2021-04-13 13:44 UTC, pmhsfelix commented on docs/auth/codegarten-api.md
> +* CodeGarten API Access Token Expiration Date - Used to determine when to request a new Access Token
- How is the client secret stored?
- How is the access token stored?

2021-04-13 13:44 UTC, pmhsfelix commented on docs/auth/codegarten-api.md
> +After the **CodeGarten Interaction Manager (IM)** gets a GitHub OAuth Access Token from the user, and after that token is stored in the database, the CodeGarten IM will generate a valid code to be ex
"gets a GitHub OAuth Access Token from the user". This means getting an access token from GitHub, based on an user delegation, right?

2021-04-13 13:44 UTC, pmhsfelix commented on docs/auth/codegarten-api.md
> +After the **CodeGarten Interaction Manager (IM)** gets a GitHub OAuth Access Token from the user, and after that token is stored in the database, the CodeGarten IM will generate a valid code to be ex
How is the code stored and its use controlled?

2021-04-13 15:20 UTC, merged